### ISSUE TITLE
TODOs in this repo should point to useful github issues

### ISSUE THREAD

**Issue by zepumph** [phetsims/kite#102] opened 2023-09-15 15:09 UTC
PhET has a policy that TODOs in production code are tied to a github issue to help in scheduling their work. This policy was created after many TODOs were created without a corresponding github issue associated with them in this repo. Never the less, this code is still production code, and TODOs should adhere to this philosophy. I'll mark TODOs in this repo to this issue now, but this should NOT be a catch all, work should be done to handle, triage, schedule and fix the work outlined by the TODOs in this repo (it is production code!).

(see work done in [phetsims/tasks#1129](https://github.com/phetsims/tasks/issues/1129) also)

**Comment by marlitas** [comment] 2023-10-30 21:56
this is a duplicate of https://github.com/phetsims/kite/issues/76.

Although it now seems like there are 94 instead of 70. Closing as a duplicate.

**Closed by marlitas** 2023-10-30 21:56 UTC

**Comment by zepumph** [comment] 2023-10-30 23:17
Updated todos pointing to this issue so it doesn't reopen tonight.

**Comment by marlitas** [comment] 2023-10-31 00:09
Ope thanks for that. I believe I did a couple of others that I should hit as well.

**Comment by marlitas** [comment] 2023-10-31 00:12
You did this everywhere. What a gem. Thanks!
